version: '3.8'

services:

  postgres-server:
    image: postgres
    restart: unless-stopped
    container_name: ${NAMEDB}
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_DB: ${DBNAME}
      PG_DATA: /var/lib/postgresql/data/pgdata
    volumes:
      - dbzabbix:/var/lib/postgresql/data
    networks:
      - zabbix

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    restart: unless-stopped
    container_name: ${NAME}
    depends_on:
      - ${NAMEDB}
    ports:
      - 10051:10051
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_DB: ${DBNAME}
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      ZBX_STARTVMWARECOLLECTORS: 10
    volumes:
      - zabbix-scripts:/usr/lib/zabbix/alertscripts
    networks:
      - zabbix

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql
    restart: unless-stopped
    container_name: ${NAMEWEB}
    depends_on:
      - ${NAMEDB}
      - ${NAME}
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_DB: ${DBNAME}
      ZBX_SERVER_HOST: ${NAME}
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Europe/Paris"
      ZBX_MAXEXECUTIONTIME: 500
    networks:
      - zabbix

volumes:
  zabbix-scripts:
  dbzabbix:

networks:
  zabbix: