version: '3.8'

services:

  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    container_name: ${NAME}
    ports:
      - ${PORTS}:3000
    environment:
      - GF_INSTALL_PLUGINS=${PLUGINS}
    volumes:
      - grafana:/var/lib/grafana

volumes:
  grafana:
