version: '3'
services:
  grafana:
    image: grafana/grafana-oss:8.5.4
    restart: always
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    volumes:
      - /apps/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    user: 'root'
